env:
- name: SVELTE_APP_REMOTE_URL
  value: "http://localhost:3000"
- name: CONTAINER_NAME
  value: "myappdevns99myappgruim"
- name: DEV
  value: "true"


gras-deploy: 
  # gras: 
  #   ssl: false
  grapi:
    ssl: false
    dev: true
  gruim:
    ssl: false
    dev: true


ingress:
  enabled: true
  hosts:
    - host: myapp.test
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
